baseurl = "https://www.cs.ucr.edu/~xyin014/"
languageCode = "en-us"
title = "Xizhe Yin @ UCR"
theme = "hugo-classic"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
enableEmoji = true
footnotereturnlinkcontents = "â†©"

canonifyURLs = true
#relativeURLs = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Publication"
    url = "/publication"
    weight = 1
[[menu.main]]
    name = "Misc"
    url = "/misc"
    weight = 2

[[menu.feed]]
    name = "About"
    url = "/about"

[params]
    description = "A simple, minimal blog for those who love text."
    footer = "Open-Source | [Github](https://github.com/goodroot/hugo-classic) | [Keybase](https://keybase.io/goodroot)"
    custom_css = ["css/theme-override.css"]
